### ISSUE TITLE
your code cannot work

### ISSUE THREAD

**Issue by LeonCgh** [LouisScorpio/datamining#5]
ValueError: Variable rnn/basic_lstm_cell/weights already exists, disallowed. Did you mean to set reuse=True in VarScope

**Comment by LouisScorpio** [comment]
@LeonCgh 可以设置reuse=True，也可以训练和预测分开进行

**Comment by LeonCgh** [comment]
非常感谢。还有一个问题是你的test data 里的mean是测试集的mean，这样子不会引入未来函数么？

**Comment by awaibj** [comment]
@LouisScorpio  我在运行第一个程序stock_predict.py时遇到类似的问题，
ValueError: Variable RNN/BasicLSTMCell/Linear/Matrix already exists, disallowed. Did you mean to set reuse=True in VarScope? 
我想咨询一下，如果要设置reuse=True ，应该在什么位置设置？
后来修改为先训练，训练完成后屏蔽train_lstm()，直接调用预测prediction()，出现如下错误：
TypeError: expected bytes, NoneType found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/python/myPyCharm/myTest/stock_predict/stock_predict_ansi.py", line 137, in <module>
    prediction()
  File "D:/python/myPyCharm/myTest/stock_predict/stock_predict_ansi.py", line 120, in prediction
    saver.restore(sess, module_file) 
 File "C:\Users\feng.si\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 1388, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\Users\feng.si\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 766, in run
    run_metadata_ptr)
  File "C:\Users\feng.si\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "C:\Users\feng.si\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "C:\Users\feng.si\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1021, in _do_call
    return fn(*args)
  File "C:\Users\feng.si\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1003, in _run_fn
    status, run_metadata)
SystemError: <built-in function TF_Run> returned a result with an error set
好像是恢复保存的模型没有成功，不知道什么原因？

**Comment by awaibj** [comment]
@LouisScorpio 刚才在你的博客上找到了ValueError: Variable RNN/BasicLSTMCell/Linear/Matrix already exists, disallowed. Did you mean to set reuse=True in VarScope?这个问题的解决办法，非常感谢！
还有一个关于模型保存的问题，我看代码里面是保存为'stock.model'，但是在读取的时候为什么变成了'module2/'，不太理解，希望得到解答，谢谢

**Comment by allan881215** [comment]
模型保存的问题，我看代码里面是保存为'stock.model'，但是在读取的时候为什么变成了'module2/'，不太理解，希望得到解答，谢谢 还有 预测的过程中遇到SystemError: <built-in function TF_Run> returned a result with an error set 是什么意思 网上找过这个问题也没看懂

**Comment by lucktiner** [comment]
@LeonCgh ,非常感谢您共享的代码，有个问题请教下：这个reuse=True 是在哪里设置的？我遇到的问题和 @awaibj 是一样的。
